version check

diff --git a/.github/workflows/check-version-bump.yaml b/.github/workflows/check-version-bump.yaml
--- a/.github/workflows/check-version-bump.yaml
+++ b/.github/workflows/check-version-bump.yaml
@@ -14,18 +14,22 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout main
-        uses: actions/checkout@v2
-        with:
-          ref: main
-
-      - name: Checkout current branch
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
       - name: Check Cargo version
         run: |
           PREV_VERSION=$(git show main:Cargo.toml | grep '^version' | awk '{print $3}')
+          if [ -z "$PREV_VERSION" ]; then
+            echo "Previous version not found."
+            exit 1
+          fi
+
           CURR_VERSION=$(grep '^version' Cargo.toml | awk '{print $3}')
+          if [ -z "$CURR_VERSION" ]; then
+            echo "Current version not found."
+            exit 1
+          fi
+
           if [ "$PREV_VERSION" = "$CURR_VERSION" ]; then
             echo "Cargo version has not incremented."
             exit 1
